version: '3.5'

volumes:
  postgres-data:

services:
  face-ai-postgres-db:
    image: ${registry}compreface-postgres-db:${POSTGRES_VERSION}
    restart: always
    container_name: "face-ai-postgres-db"
    build:
      context: ../db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  face-ai-admin:
    image: ${registry}face-ai-admin:${ADMIN_VERSION}
    restart: always
    build:
      context: ../java
      dockerfile: ../dev/Dockerfile
      target: frs_crud
    container_name: "face-ai-admin"
    ports:
      - "8081:8080"
      # - "5006:5005" # Uncomment this port mapping for application debug
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=${enable_email_server}
      - EMAIL_HOST=${email_host}
      - EMAIL_USERNAME=${email_username}
      - EMAIL_FROM=${email_from}
      - EMAIL_PASSWORD=${email_password}
      - ADMIN_JAVA_OPTS=${compreface_admin_java_options}
      - MAX_FILE_SIZE=${max_file_size}
      - MAX_REQUEST_SIZE=${max_request_size}B
    depends_on:
      - face-ai-postgres-db
      - face-ai-api

  face-ai-api:
    image: ${registry}face-ai-api:${API_VERSION}
    restart: always
    build:
      context: ../java
      dockerfile: ../dev/Dockerfile
      target: frs_core
      args:
        - ND4J_CLASSIFIER=${ND4J_CLASSIFIER}
    container_name: "face-ai-api"
    ports:
      - "8082:8080"
      # - "5005:5005" # Uncomment this port mapping for application debug
    depends_on:
      - face-ai-postgres-db
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=${compreface_api_java_options}
      - SAVE_IMAGES_TO_DB=${save_images_to_db}
      - MAX_FILE_SIZE=${max_file_size}
      - MAX_REQUEST_SIZE=${max_request_size}B
      - CONNECTION_TIMEOUT=${connection_timeout:-10000}
      - READ_TIMEOUT=${read_timeout:-60000}

  face-ai-fe:
    image: ${registry}face-ai-fe:${FE_VERSION}
    restart: always
    build:
      context: ../ui
      dockerfile: docker-prod/Dockerfile
    container_name: "face-ai-ui"
    ports:
      - "8000:80"
    depends_on:
      - face-ai-api
      - face-ai-admin
    environment:
      - CLIENT_MAX_BODY_SIZE=${max_request_size}
      - PROXY_READ_TIMEOUT=${read_timeout:-60000}ms
      - PROXY_CONNECT_TIMEOUT=${connection_timeout:-10000}ms

  face-ai-core:
    image: ${registry}face-ai-core:${CORE_VERSION}
    restart: always
    container_name: "face-ai-core"
    ports:
      - "3300:3000"
    build:
      context: ../embedding-calculator
    environment:
      - ML_PORT=3000
      - IMG_LENGTH_LIMIT=${max_detect_size}
      - UWSGI_PROCESSES=${uwsgi_processes:-2}
      - UWSGI_THREADS=${uwsgi_threads:-1}
    healthcheck:
      test: curl --fail http://localhost:3000/healthcheck || exit 1
      interval: 10s
      retries: 0
      start_period: 0s
      timeout: 1s
